-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgTla0du8t63FzjUIe
G7xiHiwza2BDvqaamvGFB3f38zGgCgYIKoZIzj0DAQehRANCAAQwbqBuwIFBWbmN
feU4dHk60SkK4pdzj9ufhvgYMyvDHAsZlZonebXNx/IpwUwFOQYcj9WiHB8nirtr
9qhAQsxH
-----END PRIVATE KEY-----